// This file is generated by `bun run generate:worker-font-source`.
// Do not edit it manually.

import archivoBlackRegularFontBytes from '../../assets/fonts/ArchivoBlack-Regular.ttf'
import { fontRegistry } from './font-registry.ts'

const bundledProjectFontBytes = [archivoBlackRegularFontBytes] as const satisfies readonly ArrayBuffer[]

export function fontSourceWorker(fontSourcePath: string): ArrayBuffer {
  const fontSourcePathIndex = (fontRegistry as readonly string[]).indexOf(fontSourcePath)

  if (fontSourcePathIndex === -1) {
    throw new Error(`Unsupported bundled project font "${fontSourcePath}".`)
  }

  const bundledProjectFontBytesValue = bundledProjectFontBytes[fontSourcePathIndex]

  if (!bundledProjectFontBytesValue) {
    throw new Error(`Missing bundled bytes for project font "${fontSourcePath}".`)
  }

  return bundledProjectFontBytesValue
}
