import { readFileSync } from 'node:fs'
import { basename, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { fontRegistry } from '../src/lib/font-registry.ts'

const outputFileUrl = new URL('../src/lib/font-source-worker.ts', import.meta.url)
const outputFilePath = fileURLToPath(outputFileUrl)
const outputDirectoryPath = fileURLToPath(new URL('../src/lib/', import.meta.url))

function createAssetImportIdentifier(fontSourcePath: string): string {
  const baseName = basename(fontSourcePath).replace(/\.[^.]+$/u, '')
  const segments = baseName.split(/[^a-zA-Z0-9]+/u).filter(Boolean)
  const [firstSegment = 'project', ...remainingSegments] = segments

  return `${firstSegment[0]?.toLocaleLowerCase('en-US') ?? ''}${firstSegment.slice(1)}${remainingSegments.map((segment) => `${segment[0]?.toLocaleUpperCase('en-US') ?? ''}${segment.slice(1)}`).join('')}FontBytes`
}

function createImportPath(fontSourcePath: string): string {
  const sourcePath = fileURLToPath(new URL(`../${fontSourcePath}`, import.meta.url))

  return relative(outputDirectoryPath, sourcePath).replaceAll('\\', '/')
}

function createGeneratedFileContents(): string {
  const imports = fontRegistry.map((fontSourcePath) => {
    const identifier = createAssetImportIdentifier(fontSourcePath)

    return `import ${identifier} from '${createImportPath(fontSourcePath)}'`
  })
  const registryEntries = fontRegistry.map((fontSourcePath) => createAssetImportIdentifier(fontSourcePath))
  const bundledProjectFontBytesDeclaration =
    registryEntries.length === 1
      ? `const bundledProjectFontBytes = [${registryEntries[0]}] as const satisfies readonly ArrayBuffer[]`
      : [
          'const bundledProjectFontBytes = [',
          ...registryEntries.map((entry) => `  ${entry},`),
          '] as const satisfies readonly ArrayBuffer[]',
        ].join('\n')

  return [
    '// This file is generated by `bun run generate:worker-font-source`.',
    '// Do not edit it manually.',
    '',
    ...imports,
    "import { fontRegistry } from './font-registry.ts'",
    '',
    bundledProjectFontBytesDeclaration,
    '',
    'export function fontSourceWorker(fontSourcePath: string): ArrayBuffer {',
    '  const fontSourcePathIndex = (fontRegistry as readonly string[]).indexOf(fontSourcePath)',
    '',
    '  if (fontSourcePathIndex === -1) {',
    `    throw new Error(\`Unsupported bundled project font "\${fontSourcePath}".\`)`,
    '  }',
    '',
    '  const bundledProjectFontBytesValue = bundledProjectFontBytes[fontSourcePathIndex]',
    '',
    '  if (!bundledProjectFontBytesValue) {',
    `    throw new Error(\`Missing bundled bytes for project font "\${fontSourcePath}".\`)`,
    '  }',
    '',
    '  return bundledProjectFontBytesValue',
    '}',
    '',
  ].join('\n')
}

const nextFileContents = createGeneratedFileContents()
const currentFileContents = readFileSync(outputFilePath, 'utf8')

if (currentFileContents !== nextFileContents) {
  await Bun.write(outputFilePath, nextFileContents)
}
